server_apps/data_transfer/GO/go.pl
server_apps/data_transfer/GO/gofile2_all.sql
server_apps/data_transfer/GO/goparser2.2.pl
source/org/zfin/db/load/1122/delete-zfin-GO-annotations.sql

Sierra, could you check if this contains all the changes you made on the ZFIN 1123 release branch? 
This is the difference between 1123 on ZFIN and 1123 on github.

Noctua merges

---

home/WEB-INF/tags/expressionAllAttributeListItem.tag
home/WEB-INF/tags/expressionHighThroughputAttributeListItem.tag
home/WEB-INF/tags/expressionLink.tag
home/WEB-INF/tags/marker-search/geneResultTable.tag
source/org/zfin/expression/presentation/MarkerExpression.java
source/org/zfin/expression/service/ExpressionService.java
source/org/zfin/marker/presentation/GeneViewController.java
source/org/zfin/marker/presentation/MarkerBean.java
source/org/zfin/marker/presentation/PublicationPrioritizationController.java
test/org/zfin/expression/service/ExpressionServiceTest.java

ZFIN-7525 add UCSC scRNA-deq link for given ensdargs
ZFIN-7525 add UCSC scRNA-deq link for given ensdargs

ZFIN-7525 add UCSC scRNA-deq link for given ensdargs

---

docker/postgresql/addUsers.sql
lib/DB_functions/addUsers.sql
server_apps/DB_maintenance/postgres/addUsers.sql

Fixes issue with authentication error we were getting today:
`FATAL:  no pg_hba.conf entry for host "::1", user "rtaylor", database "celldb", SSL off`

Add myself to list of postgres users

---

commons/env/instances.properties

ant rebuildProperties was failing -- tracked it down to this reference to "almost"

remove almost from one more spot

---

server_apps/apache/inc-redirect

I added this redirect to address the issue 7610 for the warranty page.  One note: I normally would have tested this on cell.zfin.org, but I'm having some trouble getting the deployment to work.  It may be because I wasn't able to restart apache.  So I could use a little help with that workflow. Thanks!

add 301 redirect

---

docker/compile/generate_base.sh

DOCKER:
Chrome will not let you proceed against the self-signed cert warnings unless the cert has some extended properties.  See this page:
https://eengstrom.github.io/musings/self-signed-tls-certs-v.-chrome-on-macos-catalina
and since that page lists the cert generate command without a CSR, I had to consult this to accomplish the same, but with a CSR flow:
https://security.stackexchange.com/a/176084

Fix to self-signed cert to allow chrome to proceed

---

build.gradle
build.test.gradle
home/WEB-INF/jsp/dev-tools/java-properties.jsp
source/org/zfin/framework/presentation/ApplicationContextController.java
source/org/zfin/framework/presentation/DatabaseInfoController.java
test/org/zfin/marker/presentation/DbLinkDisplayComparatorTest.java
test/org/zfin/ontology/service/OntologyServiceTest.java
test/org/zfin/sequence/blast/BlastStressLargeDBTest.java
test/org/zfin/sequence/blast/BlastStressLargeSequenceDBTest.java
test/org/zfin/sequence/blast/BlastStressSmallDBTest.java
test/org/zfin/sequence/blast/SMPExecuteBlastTest.java

ZFIN-7628 remove deprecated use in Java

ZFIN-7628 fix certain data access to be compliant to JDK 17

---

package-lock.json
package.json

revert immer package to fix indexing issue.

ZFIN-7760 (main branch)

---

package-lock.json
package.json

revert immer package to fix indexing issue.

ZFIN-7760 (release 1125)

---

package-lock.json
package.json

revert immer package to fix indexing issue.

ZFIN-7760 (release 1126)

---

home/WEB-INF/jsp/infrastructure/annual-stats-view.jsp
source/org/zfin/infrastructure/presentation/AnnualStatsController.java

ZFIN-7769 fix column / cell population of the stats table

---

source/org/zfin/marker/presentation/MutationController.java

Quick fix for serialization issue that happened as a result of the jackson upgrade.

ZFIN-7783 (release 1127): Fix Serialization Problem

---

source/org/zfin/alliancegenome/AgmRESTInterfaceAlliance.java
source/org/zfin/alliancegenome/AllianceRestManager.java
source/org/zfin/gwt/curation/server/CurationDiseaseRPCImpl.java
source/org/zfin/marker/agr/DiseaseInfo.java
source/org/zfin/marker/agr/ExperimentConditionDTO.java
source/org/zfin/mutant/service/FishService.java

The first issue is to create an Alliance AffectedGenomicModel object.
Second issues is to add chemicalOntologyId to the daf export file.

ZFIN-7810 plus SCRUM-1162

---

console.gradle
server_apps/jenkins/jobs/Genotype-Naming-Issues-Repair/config.xml
source/org/zfin/nomenclature/repair/GenotypeNamingIssues.java
source/org/zfin/nomenclature/repair/NamingIssuesReportRow.java

Add default log4j configuration file.
Add safety check for blank name.

ZFIN-7803: Fix config & add safety check

---

server_apps/data_transfer/SWISS-PROT/runUniprotPreload.sh

We had discussed adding this step to the last iteration of ZFIN-7807.

ZFIN-7807: Copy preload artifacts to network drive

---

server_apps/jenkins/jobs/Regenerate-WebHost-Curated-Databases_d/config.xml

Add 5 minute timeout to Regenerate-WebHost-Curated-Databases_d job.

ZFIN-7831 Add 5m timeout to Regenerate-WebHost-Curated-Databases_d job.

---

server_apps/DB_maintenance/Alliance/validateAllianceFiles.sh
server_apps/jenkins/jobs/Generate-Alliance-Files_m/config.xml
source/org/zfin/marker/agr/BasicReferenceInfo.java

ZFIN-7857
Use PubMed journal abbreviation in json export (getMedAbbrev).
Supply the version number of the upload to validation shell script and include in jenkins job with default of 4.1.1.

ZFIN-7857 Add version number to shell script arguments and use PubMed journal abbr.

---

source/org/zfin/db/postGmakePostloaddb/1130/db.changelog.master.xml

remove typo

---

source/org/zfin/db/postGmakePostloaddb/1129/ZFIN-7774-patch-update-rbm15b.sql
source/org/zfin/db/postGmakePostloaddb/1129/db.changelog.master.xml

Patch release 1129 to fully update
construct to replace rbm15b association to rbm15.

ZFIN-7774 Update Construct Tg(hsp70l:rbm15-FLAG)

---

source/org/zfin/feature/repository/HibernateFeatureRepository.java

Fix leftover references to ftrAssembly from refactor of FeatureLocation class that were not caught automatically.

ZFIN-7771 Finish Refactor of FeatureLocation

---

docker/compile/Dockerfile
docker/docker-compose.yml
server_apps/data_transfer/SWISS-PROT/sp_check.pl

I cleaned up the sp_check.pl file a little bit. I also added the perl debugging libraries for help during development.

ZFIN-7907 - Code cleanup for uniprot AND perl debugging in docker container

---

server_apps/ZFINPerlModules.pm
server_apps/data_transfer/SWISS-PROT/pre_loadsp.pl
server_apps/data_transfer/SWISS-PROT/sp_check.pl

Refactored pre_loadsp.pl, sp_check.pl, ZFINPerlModules.pm a bit while gathering information for the documentation.

Uniprot Refactor

---

source/org/zfin/framework/api/BinderControllerAdvice.java

Add a controller advice method to setDisallowedFields for request parameters.

ZFIN-7940: CVE Patch CVE-2022-22965

---

server_apps/solr/site_index/conf/db-data-config.xml

Add "WeakReferenceDBLinks" (similar to in HibernateSequenceRepository) to gene accession indexing and make distinct.

ZFIN-7913: Search missing some attributes.

---

source/org/zfin/framework/featureflag/FeatureFlags.java
source/org/zfin/gbrowse/GBrowseTrack.java
source/org/zfin/genomebrowser/presentation/GenomeBrowserFactory.java
test/org/zfin/gbrowse/presentation/GBrowseImageSpec.groovy

Use the new GenomeBrowserFactory method of creating GbrowseImageBuilder.

Fix GBrowseImageSpec.groovy tests 

---

home/WEB-INF/jsp/feature/feature-view.jsp
home/WEB-INF/jsp/gbrowse/gbrowse-component.jsp
home/WEB-INF/jsp/marker/clone/clone-view.jsp
home/WEB-INF/jsp/marker/transcript/transcript-view-related-transcripts.jsp
source/org/zfin/publication/JournalAbbreviationSyncTask.java

Add a null check for GBrowseImage in the react component container element. 
(I previously created two pull requests for main branch, instead of one against release branch.)

ZFIN-7962-hotfix (release-1132)

---

lib/DB_functions/get_genotype_display.sql
source/org/zfin/db/postGmakePostloaddb/1133/ZFIN-7922.sql
source/org/zfin/db/postGmakePostloaddb/1133/db.changelog.master.xml

Add fixes for genotypes with missing b1 feature.
Add fixes for genotypes with missing bns2 & bns3 features.
Add special case for en.boxb2.sgca<sup>upo351/upo351</sup>

ZFIN-7922: Add fixes for 3 genotypes missing genotype_feature relationship.

---

console.gradle
docker/docker-compose.yml
server_apps/data_transfer/PUBMED/Journal/checkAndUpdateJournals.sql
server_apps/jenkins/jobs/Check-And-Update-Journals_w/config.xml
server_apps/jenkins/jobs/Journal-Abbreviation-Sync/config.xml
source/org/zfin/publication/JournalAbbreviationSyncTask.java

SQL statement in Check-And-Update-Journals_w was not correctly joining tables so it would overwrite abbreviations.

ZFIN-7638 Fix Check-And-Update-Journals_w to not overwrite abbrevs with null

---

package-lock.json

Should fix the critical vulnerability reported by github.

ZFIN-8010 - ZFIN-8010

---

home/WEB-INF/jsp/marker/gene/gene-edit.jsp
home/WEB-INF/jsp/marker/region/region-view.jsp
home/javascript/react/components/AddEditList.js
home/javascript/react/containers/MarkerEditChromosomalLocation.js
home/javascript/react/containers/MarkerShowChromosomalLocation.js
source/org/zfin/mapping/Location.java
source/org/zfin/mapping/MarkerLocation.java
source/org/zfin/marker/presentation/ChromosomalLocationBean.java
source/org/zfin/marker/presentation/GeneEditController.java
source/org/zfin/marker/presentation/MarkerChromosomalLocationController.java
source/org/zfin/marker/repository/HibernateMarkerRepository.java
source/org/zfin/marker/repository/MarkerRepository.java
test/org/zfin/DbUnitTests.java
test/org/zfin/mapping/MappingServiceTest.java
test/org/zfin/marker/MarkerChromosomalLocationTest.java

For NTR pages, this allows adding citations to the "chromosomal location" information.  It also displays the same information to the end users on NTR view pages.

ZFIN-7945 and ZFIN-7944

---

home/WEB-INF/jsp/publication/publication-view.jsp
home/javascript/react/containers/FigurePhenotypeTable.js
home/javascript/react/containers/PublicationAttributionTable.js
home/javascript/react/containers/StrTable.js
source/org/zfin/expression/Image.java
source/org/zfin/figure/presentation/PhenotypeTableRow.java
source/org/zfin/publication/repository/HibernatePublicationRepository.java

Add ordering to image fetch for publication.
Convert class to lombok-style getters and setters.

ZFIN-8059: Return images for publication by figure orderingLabel

---

home/WEB-INF/jsp/dev-tools/home.jsp
home/WEB-INF/jsp/dev-tools/test-request-headers.jsp
source/org/zfin/framework/presentation/DatabaseInfoController.java

This doesn't fix the ultimate source of the issue, but it could be a helpful diagnostic. Example screenshot:

ZFIN-8077: Add a diagnostic page to devtools that shows request headers.

---

build.gradle
console.gradle
server_apps/ZFINPerlModules.pm
server_apps/data_transfer/NCBIGENE/NCBI_gene_load.pl
source/org/zfin/datatransfer/webservice/BatchNCBIFastaFetchTask.java
source/org/zfin/datatransfer/webservice/NCBIEfetch.java
source/org/zfin/datatransfer/webservice/NCBIRequest.java
test/org/zfin/sequence/NCBIEfetchTest.java

Add a gradle task to perform the efetch of NCBI data as a replacement for /private/bin/efetch.r.
Update the NCBI_gene_load.pl file to use the new gradle task.
Remove deprecation issues in NCBIRequest.

ZFIN-7925: Fix Failing NCBI Jenkins Load

---

test/org/zfin/alliancegenome/AllianceRestEndpointTest.java

Fixes a compiler error during "gradle test".

Change test to match the new function signature.

---

home/javascript/react/components/marker-edit/MarkerPublicNoteForm.js
source/org/zfin/sequence/blast/presentation/DisplayBlastSequenceController.java

Fix hibernate upgrade / transaction issue.
Added a fix that was generating a console error.

(Release 1133) ZFIN-8097: Fix hibernate upgrade / transaction issue.

---

source/org/zfin/framework/api/FlexibleLongDeserializer.java
source/org/zfin/marker/presentation/ChromosomalLocationBean.java
source/org/zfin/marker/presentation/ChromosomalLocationBeanValidator.java

One more int to long conversion

ZFIN-7945: One more int to long conversion

---

source/org/zfin/framework/api/FlexibleLongDeserializer.java
source/org/zfin/marker/presentation/ChromosomalLocationBean.java
source/org/zfin/marker/presentation/ChromosomalLocationBeanValidator.java

ZFIN-7945: One more int to long conversion

(Release-1133) ZFIN-7945: One more int to long conversion

---

home/WEB-INF/tags/layout/pageHeader.tag

Only show the version to root users.

ZFIN-7964: Show to root users only (1133)

---

home/WEB-INF/tags/layout/pageHeader.tag

Only show the version to root users.

ZFIN-7964: Show to root users only

---

docker/mailhog/Dockerfile

Add the Dockerfile for mailhog

ZFIN-8053: Add the Dockerfile for mailhog

---

home/WEB-INF/jsp/publication/publication-view-summary.jsp
home/javascript/angular/figure-edit.directive.js

* Fix download PDF file path
* Fix angular upgrade issue.

Patch main to fix issues discovered on 1133 deploy

---

home/WEB-INF/jsp/publication/publication-view-summary.jsp
home/javascript/angular/figure-edit.directive.js
home/javascript/angular/inline-edit-textarea.directive.js
home/javascript/angular/marker-aliases.directive.js
home/javascript/angular/marker-links.directive.js
home/javascript/angular/marker-notes.directive.js
home/javascript/angular/marker-relationships.directive.js
home/javascript/angular/marker-suppliers.directive.js
home/javascript/angular/ortho-edit.js
home/javascript/angular/quick-figure.directive.js
home/javascript/angular/str-details.directive.js
home/javascript/angular/str-sequence.directive.js

These changes were patched into 1133 and also merged into the main branch.  Must have missed the window for release 1134?

Release 1134 - Angular fixes

---

source/org/zfin/marker/presentation/SequenceController.java

Release-1134 Patch for ZFIN-8167: Make transactions read-only

---

source/org/zfin/db/postGmakePostloaddb/1135/ZFIN-8188-remove-unmatched-closing-div-tag.sql
source/org/zfin/db/postGmakePostloaddb/1135/db.changelog.master.xml

Fix unmatched closing div tag in publication abstract.

ZFIN-8188: Fix unmatched closing div tag in publication abstract

---

server_apps/DB_maintenance/build.xml
server_apps/jenkins/jobs/Load-GAF-GOA_m/config.xml

Allow running GOA GAF load with specific URLs so we can reload from previous run.

GOA-GAF with custom download URLs

---

source/org/zfin/marker/presentation/SequenceController.java

Main Branch Patch for ZFIN-8167: Make transactions read-only 

---

source/org/zfin/marker/presentation/SequenceController.java

Release-1135 Branch Patch for ZFIN-8167: Make transactions read-only

---

server_apps/solr/site_index/conf/db-data-config.xml

Fix feature query to omit null values.

ZFIN-8061: Fix feature query to omit null values

---

home/WEB-INF/jsp/fish/genotype-view.jsp
home/WEB-INF/jsp/marker/construct/construct-view.jsp
home/WEB-INF/jsp/profile/company-view.jsp
home/WEB-INF/jsp/profile/lab-view.jsp
home/css/datapage.scss

Wrap overflow of the title in the left navigation for construct pages.

ZFIN-8242: Wrap overflow of the title in the left navigation for construct pages.

---

build.gradle
console.gradle
source/org/zfin/db/postGmakePostloaddb/1136/ZFIN-8231-pre.sql
source/org/zfin/db/postGmakePostloaddb/1136/ZFIN-8231.xml
source/org/zfin/db/postGmakePostloaddb/1136/db.changelog.master.xml
source/org/zfin/thisse/ThisseLegacyImportAnalysisTask.java

A java wrapper around a bunch of sql queries for matching thisse data to our existing data.
Gradle task for running it ("gradle thisseLegacyImportAnalysisTask").
Bumped the sourceCompatibility and targetCompatibility to 15 for the use of Text Blocks.

ZFIN 8231: Report for Thisse Data Matching

---

home/WEB-INF/jsp/profile/reset-password.jsp
home/WEB-INF/tags/personEdit.tag
home/javascript/profiles/profile-edit.js
source/org/zfin/profile/UserService.java
source/org/zfin/profile/presentation/PasswordResetController.java

Fix the "generate password" button on the person edit and create pages. Fix the forgot password flow by adding transactions.

ZFIN-8270: Fix the "generate password" button

---

home/javascript/react/components/pub-tracker/PubTrackerStatus.js

Always show the "Reset topics" checkbox when status is "INDEXING".

ZFIN-8163: Publication Track Page Checkbox Handling

---

source/org/zfin/marker/presentation/MarkerLinkController.java

Return a LinkDisplay for the deleted DBLink (as JSON).

ZFIN-8268: Can't delete accession from gene edit page

---

home/css/datapage.scss

Example page with this issue: https://zfin.org/ZDB-TGCONSTRCT-210915-2
Patch to ZFIN-8242

Fix issue with wrapping in the title of the left nav

---

home/javascript/react/containers/AntibodyTable.js
home/javascript/react/containers/PublicationFigureDisplay.js

This fixes the figure display issue from ZFIN-8360

Release 1138 Patch for ZFIN-8360

---

home/WEB-INF/jsp/marker/gene/gene-edit.jsp

ZFIN-8379: Add history link to the dropdown menu of the marker page

---

home/javascript/react/containers/MarkerSequencesTable.js
source/org/zfin/sequence/service/SequenceService.java

(cherry picked from commit edef104bea5c9e01ca2a2c1d094d00e03c0f078b)

ZFIN-8387 fix overview / all sequence tab toggle for gene view page

---

source/org/zfin/db/postGmakePostloaddb/1139/ZFIN-8349.sql
source/org/zfin/db/postGmakePostloaddb/1139/db.changelog.master.xml
source/org/zfin/db/postGmakePostloaddb/db.changelog.master.xml

Fix html entity for '@' in person table (57 instances).

ZFIN-8349: Fix html entity for '@' in person table 

---

home/WEB-INF/jsp/publication/publication-view.jsp

"Show all figures" link was removed from react component and needs to be included in jsp.

Release 1138: show all figures

---

home/javascript/react/components/marker-edit/MarkerExternalNotes.js
home/javascript/react/constants/AntibodyPublications.js
home/javascript/react/containers/AntibodyEditAliases.js
home/javascript/react/containers/AntibodyEditAntigenGenes.js
home/javascript/react/containers/AntibodyEditDetails.js
home/javascript/react/containers/MarkerEditNotes.js

Add some default publications to the PublicationInputs on antibody edit page.

Release-1138: ZFIN-8380: Default Publications on PublicationInputs

---

home/javascript/react/components/marker-edit/MarkerExternalNotes.js
home/javascript/react/constants/AntibodyPublications.js
home/javascript/react/containers/AntibodyEditAliases.js
home/javascript/react/containers/AntibodyEditAntigenGenes.js
home/javascript/react/containers/AntibodyEditDetails.js
home/javascript/react/containers/MarkerEditNotes.js

Add some default publications to the PublicationInputs on antibody edit page.

ZFIN-8380: Default Publications on PublicationInputs

---

source/org/zfin/marker/service/MarkerService.java

Main Branch: ZFIN-8380: Fix issue adding supplier

---

source/org/zfin/profile/repository/HibernateProfileRepository.java
test/org/zfin/profile/repository/ProfileRepositoryTest.java

getPerson should return null if given null for ID

ZFIN-8413: getPerson should return null if given null ID

---

source/org/zfin/profile/repository/HibernateProfileRepository.java
test/org/zfin/profile/repository/ProfileRepositoryTest.java

getPerson should return null if given null for ID

 Release-1139 Hotfix for ZFIN-8413: getPerson 

---

home/css/zfin.css

Remove gray background from all figure view.

ZFIN-8369: Remove gray background from all figure view.

---

home/css/modal.scss

Fix the dialog styling issues as a result of the upgrade from jquery-modal from 0.5.9 to 0.9.2.
See: https://github.com/kylefox/jquery-modal/blob/master/jquery.modal.css

ZFIN-8442: Fix the dialog styling issues

---

source/org/zfin/sequence/reno/repository/HibernateRenoRepository.java
test/org/zfin/sequence/reno/RenoRepositoryTest.java

One note:
I left some of the hairier methods alone.  For example: getSortedRunCandidates.  Do we want to refactor those?

ZFIN-8217: RenoRepository Refactor Hibernate Queries

---

source/org/zfin/datatransfer/LoadCompleteAuthorNames.java
source/org/zfin/datatransfer/webservice/NCBIEfetch.java
source/org/zfin/db/postGmakePostloaddb/1141/ZFIN-8462-revert-ppa-changes.sql
source/org/zfin/db/postGmakePostloaddb/1141/db.changelog.master.xml
source/org/zfin/db/postGmakePostloaddb/db.changelog.master.xml
source/org/zfin/publication/presentation/PublicationService.java

Fix issue with some first names and last names getting scrambled. 
Delete potentially erroneous rows -- to be rebuilt later.

ZFIN-8462: load author names fix

---

home/WEB-INF/jsp/jbrowse/jbrowse-view.jsp
home/WEB-INF/tags/layout/pageHeader.tag
source/org/zfin/jbrowse/presentation/JBrowseController.java
source/org/zfin/jbrowse/presentation/JBrowseImage.java

ZFIN-8451: Full jBrowse UI page

---

home/WEB-INF/tags/layout/dataPage.tag
home/WEB-INF/tld/zfin-fn.tld
source/org/zfin/framework/presentation/ZfinJSPFunctions.java

- Only show counts on the publication page left nav if user is root

ZFIN-8461: publication page left nav count root-only

---

home/WEB-INF/jsp/mapping/mapping-detail.jsp
home/WEB-INF/tags/PhysicalMapAndBrowserSection.tag
source/org/zfin/jbrowse/presentation/JBrowseImageBuilder.java
source/org/zfin/mapping/presentation/MappingDetailController.java

Simple jBrowse on mapping detail page
Ignore highlighting in jBrowse for now.

ZFIN-8450 and ZFIN-8452: jBrowse on mapping detail page, remove highlighting for jBrowse

---

server_apps/jenkins/jobs/Gene-Association-File-Export_w/config.xml

Copy all the generated artifacts from the jenkins job into the downloads directory:
gene_association.zfin.gz
gpad2.0.zfin.gz
gene_association2.2.zfin.gz
gene_association2.2_automated_only.zfin.gz 
gp2protein.zfin.gz
zfin.gpi.gz
zfin.gpi2.gz

ZFIN-8474: Copy all artifacts into place from Gene-Association-File-Export_w

---

source/org/zfin/db/postGmakePostloaddb/1141/ZFIN-8447-construct-edit.sql
source/org/zfin/db/postGmakePostloaddb/1141/db.changelog.master.xml

ZFIN-8447: Update construct from "Tg(rho:SFtag-whrna)" to "Tg(rho:SFtag-whrna,myl7:EGFP)"

ZFIN-8447: Update construct to "Tg(rho:SFtag-whrna,myl7:EGFP)"

---

source/org/zfin/db/postGmakePostloaddb/1141/ZFIN-8448-withdraw-fish-with-reference.sql

I'm not sure how, but I got the wrong fish ID in the first version.  Here's the fix.

ZFIN-8448: Fix wrong ID

---

source/org/zfin/db/postGmakePostloaddb/1141/ZFIN-8467-construct-edit.sql
source/org/zfin/db/postGmakePostloaddb/1141/db.changelog.master.xml

Edit construct: Tg(EMTB:3xGFP) -> Tg(6xUAS:EMTB-3xGFP)

ZFIN-8467: Edit construct

---

home/WEB-INF/jsp/profile/person-submit.jsp
source/org/zfin/profile/PersonSubmission.java
source/org/zfin/profile/presentation/PersonSubmissionController.java

Add country to user registration form.

ZFIN-8466: Add country to user registration form.

---

source/org/zfin/db/postGmakePostloaddb/1141/ZFIN-8470-construct-edit.sql
source/org/zfin/db/postGmakePostloaddb/1141/db.changelog.master.xml

Change association between constructs and YFP to lanYFP.

ZFIN-8470: construct edit YFP -> lanYFP

---

home/WEB-INF/jsp/figure/image-view-prototype.jsp
source/org/zfin/framework/presentation/ImageNavigationMenu.java
source/org/zfin/publication/presentation/ImageViewController.java

Hide Figure Caption if there is no caption.
Fix acknowledgments section on image page to match figure page

ZFIN-8475: Image Prototype Tweaks

---

home/WEB-INF/jsp/infrastructure/home/home-additional-resources.jsp
home/WEB-INF/tags/layout/pageFooter.tag

Update other links to gbrowse too.

ZFIN-8451: Update other links to gbrowse too

---

home/WEB-INF/tags/PhysicalMapAndBrowserSection.tag

Change the label on link to zfin jbrowse to be "ZFIN JBrowse" if flag is enabled.

ZFIN-8450:

---

source/org/zfin/feature/repository/FeatureService.java
source/org/zfin/gbrowse/GBrowseTrack.java
source/org/zfin/genomebrowser/GenomeBrowserTrack.java
source/org/zfin/jbrowse/presentation/JBrowseImage.java

ZFIN-7824: Add assembly to JBrowse widget

---

server_apps/DB_maintenance/build.gradle
server_apps/DB_maintenance/build.xml

Change URLs to match new format.

ZFIN-8529: Change geneontology.org URLs to match new format.

---

source/org/zfin/marker/repository/HibernateMarkerRepository.java

Eager load some relationships.
Alternatively, we could do something like this on OntologyService:
```
for(OmimPhenotypeDisplay omimPhenotypeDisplay : omimDisplays){
List<Marker> tempMarkerList = omimPhenotypeDisplay.getZfinGene();
if(tempMarkerList != null){
for(Marker tempMarker : tempMarkerList){
if(tempMarker != null){
//Eager loading from database to prevent error in JSP
// (https://zfin.atlassian.net/browse/ZFIN-8545)
log.debug("tempMarker.getAbbreviation() = " + tempMarker.getAbbreviation());
}
}
}
}
```

ZFIN-8545: Pull request for release-1142

---

source/org/zfin/jbrowse/presentation/JBrowseImage.java
source/org/zfin/jbrowse/presentation/JBrowseImageBuilder.java

I moved the code comment that disables highlighting from the "set" part of the code to the "get" part of the code that generates the image URL.

ZFIN-8570: Tweak to jbrowse highlighting to disable for now.

---

server_apps/DB_maintenance/build.xml
source/org/zfin/database/ZdbIdGenerator.java
source/org/zfin/datatransfer/flankingsequence/FlankSeqProcessor.java
source/org/zfin/feature/repository/HibernateFeatureRepository.java
source/org/zfin/mapping/VariantSequence.java

- Add some more output to the Flank Sequence Processor job
- When transactions are committed mid-job, open another transaction
- Cleanup: unused imports and lombokify

ZFIN-8586: load-flank-seq job fix

---

source/org/zfin/marker/presentation/SequenceController.java

(cherry picked from commit db646fbf47c55385c78a8884ace2ffd9e3d8fee8)

ZFIN-8597 add transaction to sequence controller

---

source/org/zfin/db/postGmakePostloaddb/1143/ZFIN-8531-construct-relationship.sql

which then populates marker_relationship with the regen_construct_marker method.

ZFIN-8531: Fix by inserting relationships to construct_marker_relationship

---

home/WEB-INF/jsp/feature/feature-view-variants.jsp

Break long sequence so it doesn't extend off the side of the page.

ZFIN-8622: Fix display of long sequence not wrapping

---

server_apps/data_transfer/GO/gofile2_all.sql

Change located_in to part_of if relationship is for a descendant of "protein containing complex".

ZFIN-8491: Change located_in to part_of 

---

server_apps/data_transfer/GO/gofile2_all.sql
server_apps/data_transfer/NCBIGENE/NCBI_gene_load.pl
server_apps/data_transfer/SWISS-PROT/ProblemFileUtil.pm
server_apps/data_transfer/SWISS-PROT/README
server_apps/data_transfer/SWISS-PROT/clean_prob_files.pl
server_apps/data_transfer/SWISS-PROT/move_prob_files.pl
server_apps/data_transfer/SWISS-PROT/rearrange_prob_files.pl
server_apps/data_transfer/SWISS-PROT/runUniprotPreload.sh
server_apps/data_transfer/SWISS-PROT/sp_check.pl
server_apps/data_transfer/SWISS-PROT/sp_delete.sql
server_apps/data_transfer/SWISS-PROT/sp_load.sql
server_apps/data_transfer/SWISS-PROT/validate_prob_files.pl
server_apps/jenkins/jobs/NCBI-Gene-Load_w/config.xml
server_apps/jenkins/jobs/Uniprot-Preload/config.xml
server_apps/jenkins/jobs/Uniprot-Production-Load/config.xml
source/org/zfin/uniprot/NcbiMatchThroughEnsemblTask.java

These are changes that were made in release-1145 that relate to the UniProt load. This patch is to bring those changes into 1144 for running on PROD before deploying release-1145.

Backport of UniProt Changes from release-1145 to release-1144

---

server_apps/data_transfer/SWISS-PROT/sp_load.sql

See comment from Doug on ticket # ZFIN-8492

ZFIN-8492: revert changes

---

home/WEB-INF/jsp/search/prototype-results.jsp
home/WEB-INF/tags/search/allFacetsModal.tag
home/WEB-INF/tags/search/facetAutocomplete.tag
home/javascript/react/containers/QuickSearchDialog.js
home/javascript/react/index.js
home/javascript/react/state/ZfinEventBus.js

Convert angular-based dialog on the search page to use react. 
Simplify data passing mechanism to be more direct instead of using jQuery.
Introduce "EventBus" as a way of passing data to a react component--basically, a more generalized version of the navigation counter.

ZFIN-8510: Convert angular to react

---

source/org/zfin/db/postGmakePostloaddb/1146/ZFIN-8621.sql

Account for conflicts to existing records.

ZFIN-8621: Fix for liquibase failing on conflict

---

source/org/zfin/db/postGmakePostloaddb/1148/ZFIN-8768.sql
source/org/zfin/db/postGmakePostloaddb/1148/db.changelog.master.xml

ZFIN-8768 and ZFIN-8777

---

lib/DB_functions/Regen_genox/regen_cleanup_renamed_tables.sql
server_apps/DB_maintenance/warehouse/regenPhenotypeMartCleanup.sh

- forgot to include the "select" part of running a function
- take into account constraints when dropping indexes

ZFIN-8351: One more bugfix:

---

source/org/zfin/feature/repository/FeatureRepository.java
source/org/zfin/feature/repository/HibernateFeatureRepository.java
test/org/zfin/feature/repository/FeatureRepositoryTest.java

This reverts commit 0de6e4dcb0d5e27f4f92752ec72bf2a82b1d53f4.

Revert "ZFIN-8345 (#753)"

---

home/WEB-INF/jsp/marker/gene/gene-view-disease-via-ortholog.jsp
home/WEB-INF/jsp/marker/gene/gene-view-pathways.jsp
home/WEB-INF/jsp/marker/gene/gene-view-plasmids.jsp
home/WEB-INF/tags/externalLink.tag
home/WEB-INF/tags/ontologyTermLinks.tag
home/WEB-INF/tags/orderThis.tag
home/javascript/react/components/AttributionLink.js
home/javascript/react/components/ExternalLinkMaybe.js
home/javascript/react/components/SupplierList.js
home/javascript/react/containers/GeneMarkerRelationshipsTable.js
home/javascript/react/containers/GeneOntologyRibbon.js
home/javascript/react/containers/OrthologyTable.js
home/javascript/zfin-common/index.js
home/javascript/zfin-common/open-external-links-in-new-tab.js
source/org/zfin/framework/presentation/EntityPresentation.java
source/org/zfin/mutant/presentation/MarkerGoEvidencePresentation.java
source/org/zfin/sequence/presentation/DBLinkPresentation.java

- In JSPs, replace '<a href...' tags with '<zfin2:externalLink...' where appropriate
- In React components, replace the '<a ...' jsx tags with a new react component '<ExternalLinkMaybe ...' that opens in a new tab if not a local link

ZFIN-7053: Make external links open in new tab on gene page.

---

lib/DB_functions/convert_gene_to_ncrnag.sql
lib/DB_functions/convert_gene_to_type.sql
lib/DB_functions/convert_marker_type.sql
source/org/zfin/db/postGmakePostloaddb/1148/ZFIN-8809.sql

expand convert_gene_to... functionality to support any marker type.
- Also, if expression_experiment2 table references marker, propagate that change

ZFIN-8809: Change ZDB-LINCRNAG-050208-65 to ZDB-GENE-050208-804

---

source/org/zfin/marker/Marker.java
source/org/zfin/marker/presentation/SequenceTargetingReagentAddController.java

Amy pointed out that the correct prefix for Morpholinos is MO and not MRPHLNO

ZFIN-8599: fix MO abbrev

---

source/org/zfin/marker/presentation/SequenceTargetingReagentAddBeanValidator.java
source/org/zfin/marker/presentation/SequenceTargetingReagentAddController.java

I fixed a couple more places where we need to get the marker type based on "MO" not on "MRPHLNO"

ZFIN-8599: Fix remaining issue with adding morpholino

---

home/WEB-INF/jsp/profile/person-submit.jsp

- Change label from ‘Role’ to ‘Role/Position’.
- Change label from ‘Lab/Company’ to ‘Lab’
- Make ‘Role/Position’ required if ‘Lab’ is populated

ZFIN-8951: Change labels on new person form

---

test/org/zfin/sequence/SequenceRepositoryTest.java

We have a case to fix it (https://zfin.atlassian.net/browse/ZFIN-8955).

Fix failing test by skipping it for the next 8 months. 

---

lib/DB_functions/is_numeric.sql
source/org/zfin/feature/FeaturePrefix.java
source/org/zfin/feature/FeatureTracking.java
source/org/zfin/feature/repository/FeatureRepository.java
source/org/zfin/feature/repository/HibernateFeatureRepository.java
source/org/zfin/gwt/curation/ui/feature/AbstractFeaturePresenter.java
source/org/zfin/gwt/curation/ui/feature/FeatureAddPresenter.java
test/org/zfin/DbUnitTests.java
test/org/zfin/feature/FeatureTrackingTest.java

Account for feature tracking table when calculating the next zf line number for the "Add New Feature" interface in the curation UI.

ZFIN-8937: Fix the next zf line number for "Add New Feature"

---

home/javascript/react/components/curate-construct/ConstructMarkerAutocomplete.js

Remove this DOMAIN variable that I was using during development.

Remove DOMAIN variable

---

source/org/zfin/uniprot/secondary/handlers/MarkerGoTermEvidenceActionCreator.java

Load was failing when the mapping file for ec2go was mapping to a go term that we don't have loaded in our DB. This patch skips those terms.

Uniprot Secondary Load Hotfix for Missing Go Term

---

home/javascript/react/containers/LinkAuthors.js
source/org/zfin/datatransfer/webservice/NCBIEfetch.java
source/org/zfin/publication/presentation/PublicationEditController.java

Example:
https://github.com/ZFIN/zfin/assets/90803397/d1b9c02c-3e68-4be9-a2c1-84b069da4614

ZFIN-9041: Add author refresh button on link author page

---

home/WEB-INF/conf/download-registry.xml
server_apps/data_transfer/Downloads/DownloadFiles.sql

The current xml handler doesn't support this for the same filename, so we have to generate a copy of the file with a different name.

ZFIN-8960 & ZFIN-8961: Put the same file in multiple categories

---

source/org/zfin/database/repository/PostgresRepository.java

fix DB hibernate query for PG connections

---

source/org/zfin/marker/agr/ConditionRelationDTO.java
source/org/zfin/marker/agr/DiseaseInfo.java
source/org/zfin/mutant/repository/HibernateMutantRepository.java

We only use a high-level slim for conditionClassId and otherwise conditionId

Add experiment conditions for alliance phenotype file

---

home/WEB-INF/conf/download-registry.xml
server_apps/data_transfer/Downloads/DownloadFiles.pl
server_apps/data_transfer/Downloads/DownloadFiles.sql

ZFIN-8962:	Create Download file: Expression phenotypes with single chemical in environment in WT fish
ZFIN-9065:	Create Download file: Phenotypes with single chemical in environment in WT fish
ZFIN-9066:	Create Download file: Phenotypes modified by chemical-ameliorated or exacerbated data
ZFIN-9067:	Create Download file: Disease models that include chemical				
ZFIN-9094:	Fix bug in wildtype-expression_fish.txt download file missing filter

ZFIN-9067 & ZFIN-9066 & ZFIN-9065 & ZFIN-8962 & ZFIN-9094: Toxicology Downloads

---

server_apps/jenkins/jobs/Index-Faceted-Search-Step-2-Solr_d/config.xml
server_apps/jenkins/jobs/Index-Faceted-Search-Step-3-Cleanup_d/config.xml
server_apps/jenkins/trigger.production.properties

ZFIN-9141: Change the schedule for the indexer cleanup job (once per week at 8am on Tuesday). Timeout after 3 minutes (usually it takes about 10 seconds to run).

ZFIN-9141: Change the schedule for the indexer cleanup job to weekly

---

server_apps/data_transfer/Downloads/DownloadFiles.sql

Move definition of temp table experiment_condition_with_zeco_and_chebi to before first use

ZFIN-9065 bugfix for DownloadFiles.sql

---

build.gradle
server_apps/DB_maintenance/warehouse/regenExpressionMart.sh
server_apps/DB_maintenance/warehouse/regenPhenotypeMart.sh
server_apps/data_transfer/Downloads/DownloadFiles.pl
server_apps/data_transfer/Downloads/GFF3/generateGff3.groovy
server_apps/data_transfer/Downloads/GFF3/knockdown_reagents/E_zfin_knockdown_reagents.gff3.example
server_apps/data_transfer/Downloads/intermineData/dumper.sh
server_apps/data_transfer/GO/go.pl
server_apps/data_transfer/GO/goparser.pl
server_apps/data_transfer/GO/gpad.pl
server_apps/jenkins/jobs/Download-Files_d/config.xml

Fix some issues encountered on the new trunk with docker.  These came about while running jenkins jobs for download files and faceted indexer.

Trunk docker fix

---

server_apps/data_transfer/Downloads/DownloadFiles.sql

This was using the base view before adding chemicals to it.

Bugfix: Use the correct temp view

---

source/org/zfin/db/postGmakePostloaddb/1156/ZFIN-9018.sql

(cherry picked from commit a4859fbea4957cdf59850d8c1945dc255b0ebd33)

make mesh_chebi justification use chaining justification

---

home/javascript/react/components/form/InputField.js
home/javascript/react/components/marker-edit/SequenceTargetingReagentSequenceFields.js

Allow transforming text when pasted into the STR sequence input.

ZFIN-9058: Remove spaces on pasted sequences

---

test/org/zfin/sequence/blast/BlastRepositoryTest.java

Fix test to match method signature change in getAllEnsemblGenes

Fix-Test: getAllEnsemblGenes

---

source/org/zfin/publication/presentation/PublicationTrackingController.java

HotFix: Cannot claim publications due to null value in PublicationTrackingController.java

---

home/WEB-INF/jsp/construct/construct-rename.jsp
home/javascript/react/components/curate-construct/ConstructCassetteListEditor.tsx
home/javascript/react/components/curate-construct/ConstructRelationshipsTable.tsx
home/javascript/react/components/curate-construct/ConstructTypes.ts
home/javascript/react/components/curate-construct/CurateConstructEdit.tsx
home/javascript/react/components/curate-construct/CurateConstructForm.tsx
home/javascript/react/components/curate-construct/CurateConstructNew.tsx
source/org/zfin/construct/name/Cassettes.java
source/org/zfin/construct/name/ConstructName.java
source/org/zfin/construct/name/Promoter.java
source/org/zfin/construct/presentation/ConstructAddController.java
source/org/zfin/construct/presentation/ConstructComponentService.java
source/org/zfin/construct/presentation/ConstructEditController.java
source/org/zfin/publication/presentation/PublicationAPIController.java

These changes allow editing constructs. I expect we will want to get some feedback and refine it further.

ZFIN-9247: Incremental improvement to construct edit

---

build.gradle
server_apps/DB_maintenance/pub_check_and_addback_volpg.pl
server_apps/data_transfer/PUBMED/Journal/checkAndUpdateJournals.pl
server_apps/data_transfer/PUBMED/Journal/mergeJournals.pl
server_apps/data_transfer/PUBMED/complete_auther_names.pl
server_apps/data_transfer/PUBMED/pubActivation.groovy

- Add more logging with timestamps to help troubleshoot
- Clean up template syntax ()
- Use conditionals in pubActivation.groovy to avoid `file not found` errors in `\copy` commands

ZFIN-9283: Improve logging for troubleshooting jenkins job

---

server_apps/data_transfer/Downloads/intermineData/dumper.sh

Fixing issue where previous commit accidentally changed:
`home/data_transfer` to `server_apps/data_transfer`
for deletion

Fix dumper.sh file path

---

home/javascript/react/containers/FPBase.js
source/org/zfin/fish/presentation/EfgAPIController.java
source/org/zfin/marker/repository/HibernateMarkerRepository.java
source/org/zfin/marker/repository/MarkerRepository.java

Show a more informative error message when a fluorescent protein isn't in our DB yet:

ZFIN-9294: Error message for adding fluorescent protein

---

cgi-bin/merge_markers.pl

- Fix the recursive walk through foreign keys to handle different schemas
- Add DB HOST for use in case this script runs on a different host than the DB
- Account for the possibility that a data alias may already exist before creating a new one

ZFIN-9276: Merge Markers

---

home/javascript/react/components/curate-construct/ConstructRelationshipsTable.tsx
source/org/zfin/publication/presentation/PublicationAPIController.java

- Not all constructs are of type 'Transgenic Construct'
- Filter list of constructs by pub to only include those in construct relationships by pub

ZFIN-9338: Fixes to construct edit functionality

---

build.gradle

- gradle getdb     (download the db data)
- gradle loaddb    (load the db data)
- gradle getsolr   (download the solr data)
- gradle loadsolr  (load the solr data)

Adding some aliases so we can run:

---

source/org/zfin/feature/FeatureDnaMutationDetail.java
source/org/zfin/feature/repository/FeatureRepository.java
source/org/zfin/feature/repository/HibernateFeatureRepository.java
source/org/zfin/gwt/curation/server/FeatureRPCServiceImpl.java
source/org/zfin/infrastructure/delete/DeleteFeatureRule.java

- Give helpful errors for issues with deleting features that have FeatureDnaMutationDetail.

ZFIN-9213: Improve error messages

---

home/javascript/__tests__/QuickSearchDialog.test.js
home/javascript/react/containers/QuickSearchDialog.js
package.json

- Expected crispr1 searches weren't flagging correctly.
- Add unit testing for JS.

ZFIN-9282: Fix issue in QuickSearchDialog.js

---

home/WEB-INF/jsp-include/tag-import.jsp
home/WEB-INF/tags/layout/page.tag
home/WEB-INF/tld/zfin-tags.tld
source/org/zfin/framework/presentation/tags/ClearBufferTag.java

Remove the whitespace at the top of pages' source code

---

console.gradle
home/WEB-INF/jsp/publication/edit-publication.jsp
home/WEB-INF/tags/publicationForm.tag
home/javascript/react/containers/FigureEdit.js
home/javascript/react/containers/PubEditFiles.js
home/javascript/react/containers/PubFileCheck.tsx
server_apps/jenkins/email-configuration.production.properties
server_apps/jenkins/jobs/Find-Empty-Publication-Files_w/config.xml
server_apps/jenkins/trigger.production.properties
source/org/zfin/publication/FindEmptyPublicationFilesTask.java
source/org/zfin/publication/PublicationFile.java
source/org/zfin/publication/presentation/PublicationFileController.java
source/org/zfin/publication/presentation/PublicationService.java
source/org/zfin/publication/repository/HibernatePublicationRepository.java
source/org/zfin/publication/repository/PublicationRepository.java

Added a jenkins job for finding empty files.
Added a UI element to help make it more obvious when an empty file is uploaded:
https://github.com/user-attachments/assets/881dd776-234e-46f8-845a-ee07d72e8eb5

ZFIN-9356: Add measures to find empty files for pubs

---

source/org/zfin/infrastructure/EndpointPrinter.java

I wanted to get a list of endpoints. This component class will print out all the endpoints in the application at startup time.  eg:
```
Endpoint: [/api/expression] | HTTP Method: [] | Controller: org.zfin.agr.DataController | Method: getFirstExpression
Endpoint: [/alliance/dashboard] | HTTP Method: [] | Controller: org.zfin.alliancegenome.presentation.AllianceDashboardController | Method: allianceDashboard
Endpoint: [/ontology/show-expressed-genes/{zdbID}] | HTTP Method: [] | Controller: org.zfin.anatomy.presentation.AnatomyAjaxController | Method: showExpressedGenes
Endpoint: [/ontology/show-expressed-insitu-probes/{zdbID}] | HTTP Method: [] | Controller: org.zfin.anatomy.presentation.AnatomyAjaxController | Method: showExpressedInSituProbes
Endpoint: …
```

Helpful debugging output to list all endpoints at startup

---

source/org/zfin/marker/repository/HibernateMarkerRepository.java

Fix to error in logs of:
```
org.hibernate.sql.exec.ExecutionException: A problem occurred in the SQL executor : Error advancing (next) ResultSet position [You can't operate on a closed ResultSet!!!]
```

ZFIN-9414: (Triple Upgrade) Fix hibernate error

---

docker/jenkins/Dockerfile

Fixed the multiline wrap for the final argument to bash

Fix jenkins startup command

---

source/org/zfin/mapping/GenomeLocation.java

(cherry picked from commit 2c837ff18ca3bdf103ce85cc4ff489fea480c213)

ZFIN-9351 adjust link to UCSC genome browser

---

source/org/zfin/expression/repository/HibernateExpressionRepository.java

Bring textblock changes from tomcat10 branch into main to sync up the two branches

Textblock changes from tomcat10 into main

---

source/org/zfin/marker/repository/HibernateMarkerRepository.java
source/org/zfin/search/presentation/SearchPrototypeController.java

Add handling for binding list of IDs with very large number of IDs.
This change is already in release-1164 branch. Need to add it to main.

ZFIN-9401: handle getMarkersByZdbIDs(ids) when ids is larger than max allowed by postgresql

---

source/org/zfin/profile/service/ProfileService.java

Fix the ordering of AccountInfo and Person creation for new entity mapping

Fix Test: createPerson

---

home/WEB-INF/jsp/infrastructure/annual-stats-view.jsp
source/org/zfin/infrastructure/presentation/AnnualStatsController.java

By default only show the most recent 10 years. Give select boxes for choosing a different range.

ZFIN-9226: Show smaller set of years for annual stats by default.

---

server_apps/solr/site_index/conf/db-data-config.xml

Remove legacy code referencing expression_experiment and replace with correct column name for expression_experiment2

Fix db-data-config.xml for expression_experiment2

---

home/javascript/react/api/figure.js
home/javascript/react/containers/FigureEdit.js
home/javascript/react/utils/inline-edit-textarea.js

Display error if curator tries to set figure label to the same as an existing label.

ZFIN-9579: Display error on figure label update (1166)

---

source/org/zfin/indexer/ChebiFishModelIndexer.java
source/org/zfin/indexer/ChebiPhenotypeIndexer.java
source/org/zfin/indexer/FishModelIndexer.java
source/org/zfin/indexer/GenesInvolvedIndexer.java
source/org/zfin/indexer/PublicationExpressionIndexer.java
source/org/zfin/indexer/TermPhenotypeIndexer.java
source/org/zfin/indexer/UiIndexer.java

(cherry picked from commit 88082e1da36276e583bcd4a43639e9036440c7aa)

ZFIN-9584 adjust deletion of ui fast search tables due to change in Annotation

---

source/org/zfin/sequence/blast/AbstractWublastBlastService.java
source/org/zfin/sequence/blast/repository/HibernateBlastRepository.java

Refactor getAllValidAccessionNumbers

ZFIN-9621: Refactor for readability and improve logging

---

home/WEB-INF/jsp/curation/curation.jsp
source/org/zfin/curation/presentation/CurationController.java
source/org/zfin/framework/featureflag/FeatureFlagEnum.java
source/org/zfin/gwt/curation/ui/CurationModuleType.java

This reverts commit 045f08e2490c9906eac4449595060cb514f27c08.
In our construct edit meeting, we decided it wasn't worth it to make the changes to relabel the different versions.

Revert "ZFIN-9567: Make the new construct edit tab the default choice…"

---

home/javascript/react/containers/Jbrowse2Image.js

ZFIN-9575: jBrowse2 image needs knockdown reagent track

---

server_apps/jenkins/trigger.production.properties
source/org/zfin/db/postGmakePostloaddb/1170/ZFIN-9688-01-pre.sql
source/org/zfin/db/postGmakePostloaddb/1170/ZFIN-9688-03-post.sql
source/org/zfin/db/postGmakePostloaddb/1170/ZFIN-9688.xml
source/org/zfin/db/postGmakePostloaddb/1170/db.changelog.master.xml

Pause Regenerate-Chromosome-Mart_d for now

ZFIN-9688: Restore sequence_feature_chromosome_location_generated

---

console.gradle
docker/docker-compose.yml
docker/ncbiload-inputs/README.md
docker/ncbiload-inputs/set1/.gitignore
docker/ncbiload/Dockerfile
server_apps/data_transfer/NCBIGENE/NCBI_gene_load.pl
server_apps/jenkins/jobs/NCBI-Gene-Load-Java/config.xml
source/org/zfin/datatransfer/ncbi/NCBIDirectPort.java
source/org/zfin/datatransfer/ncbi/NCBIReportBuilder.java
source/org/zfin/datatransfer/ncbi/port/PortHelper.java
source/org/zfin/datatransfer/ncbi/port/PortSqlHelper.java
source/org/zfin/datatransfer/webservice/BatchNCBIFastaFetchTask.java
source/org/zfin/framework/exec/ExecProcess.java
test/org/zfin/datatransfer/ncbi/NCBIPortTest.java

Port logic of perl directly over to Java without translating to idiomatic Java first.

NCBI Load: Direct Port to Java

---

.gitignore
home/uniprot/zfin-report-sample.html
home/uniprot/zfin-report-template.html
server_apps/data_transfer/NCBIGENE/NCBI_gene_load.pl
server_apps/data_transfer/NCBIGENE/clear-artifacts.sh
server_apps/jenkins/jobs/NCBI-Gene-Load-Java/config.xml
source/org/zfin/datatransfer/ncbi/NCBIDirectPort.java
source/org/zfin/datatransfer/ncbi/NCBIReportBuilder.java
source/org/zfin/datatransfer/ncbi/port/PortHelper.java
source/org/zfin/datatransfer/report/model/LoadReportAction.java
source/org/zfin/datatransfer/report/model/LoadReportActionLink.java
source/org/zfin/datatransfer/report/model/LoadReportActionTag.java
source/org/zfin/datatransfer/report/model/LoadReportMeta.java
source/org/zfin/datatransfer/report/model/LoadReportSummary.java
source/org/zfin/datatransfer/report/model/LoadReportSummaryTable.java
source/org/zfin/datatransfer/report/model/LoadReportTableHeader.java
source/org/zfin/datatransfer/report/model/ZfinReport.java
source/org/zfin/datatransfer/report/util/ZfinReportSerializationUtil.java
source/org/zfin/datatransfer/webservice/BatchNCBIFastaFetchTask.java
source/org/zfin/datatransfer/webservice/NCBIEfetch.java
source/org/zfin/datatransfer/webservice/NCBIRequest.java
test/org/zfin/datatransfer/report/model/LoadReportActionTest.java
test/org/zfin/datatransfer/report/model/LoadReportMetaTest.java
test/org/zfin/datatransfer/report/model/LoadReportSummaryTest.java
test/org/zfin/datatransfer/report/model/ZfinReportTest.java
test/org/zfin/datatransfer/report/util/ZfinReportSerializationUtilTest.java
test/org/zfin/sequence/NCBIEfetchTest.java

- Java classes for serializing to json report
- Add Inserts and Deletes to NCBI load report.
- Add updates to report

ZFIN-9745: Add deleted genes (and other accessions) to load report

---

home/javascript/react/components/curate-construct/ConstructRelationshipsTable.tsx
home/javascript/react/components/curate-construct/ConstructTypes.ts
home/javascript/react/components/curate-construct/CurateConstructEdit.tsx
home/javascript/react/components/curate-construct/CurateConstructEditContext.tsx
home/javascript/react/components/curate-construct/CurateConstructForm.tsx

- Clear form when appropriate.
- Remove "back" link.

ZFIN-9713 & ZFIN-9704: Construct Edit Updates

---

server_apps/jenkins/trigger.production.properties

Removed unnecessary line breaks from NCBI-Gene-Load-Java cron job.

ZFIN-9968: NCBI-Gene-Load-Java cron job entry
